nonsense= ['The nimble mind applied the snobbish attempt with the finest care in the world in fear of bending the pins.',
'The equal form convinces the change in attitude amongst the entirety of the engineering team as they prepared for takeoff.',
'The voice set up the fascinated noise as the wind left a fart through the corridor in the footprint.',
'The amount of dry kiss will surely motivate the sports team to accelerate through the greatest pace on earth.',
'The kiss audit the icky advertisement with the superintendant will counsel the emotional arrangement in their special way.',
'The pleasure assembled the drunk wash along with the light wash so that we could complete the task.',
'He looked like an absolute cookie, failing to impress the harsh critics on the team of Great Danes.',
'The theatre stage at the top of the world decided to withdraw the draconian sounds of misery.',
'This life is nothing short of a condensing spark of sacred coherence because we exist as bio-feedback.',
'The furiously diligent disease judged the runway look of the season for the tenth year running.',
'The defective disease inspired the busiest sea harbor of the eastern inlands of the Kansas coast.',
'The yummy change manage the war effort on the front lines along with the hall monitor.',
'The exciting current bought the slimy story as they stumbled sideways into the dimly lit hallway.',
'The edge check in the fearful glass became a fine mist of color and wisdom.',
'The sleepy sheep identified the name of the best qualifying villain for the maze job.',
'The thundering time retain the rate of change as the pace accelerates through the corner.',
'The game levels are generated in a step-wise towering method, allowing for automatic consensus.',
'The fire defined the hallowed, centuries-old colorful print that has persisted throughout the ages.',
'The taste arranges the weary detail with a fuzzy and blurred outlook on life.',
'The motion entertains the butter while the hate probes the year in and out.',
'The step drafted the odd page full of fury, pain, anger and frustration.',
'The furry effect views the look as one of great tuna cramming time.',
'The line cooks help the astonishing pleasure as everyone is always chewing gum.',
'Our conversations with other seekers have led to an evolving of supra-zero-point consciousness.',
'Reality has always been overflowing with starseeds whose hearts are baptized in stardust.',
'The page dispatched the hungry kiss with the utmost speed and thirst.',
'The hulking meal accumulated the balance of steel sheets and dunking fronds.',
'Credit card services such as the car-run operations were conceived in Singapore.',
'The temporal differential we call wakefulness is the cosmic interaction of subatomic particles operating in the quantum field.',
'The leap represents a fundamental universal constant that speculate upon in the macro scale of wave form frequencies.',
'Our conversations with other dreamers have led to an unfolding of ultra-magical consciousness of caffeine addiction.',
'We must learn how to lead joyous lives in the face of delusion and in the mouth of utmost buffoonery.',
'Reality has always been buzzing with warriors whose dreams are nurtured by the balance point at the tongue tip.',
'Only an entity of the world may integrate this vision of consciousness, so we can no longer afford to live.',
'We are in the midst of a slime unfolding of understanding that will enable us to access the planet itself.',
'Bondage is born in the gap where interconnectedness has been excluded from the VIP table at the barseat of life.',
'The quantum matrix is radiating ultrasonic energy because you must realize we exist as a resonance cascade of cicadas chirping.',
' Consciousness consists of four-dimensional superstructures of quantum energy yet exists within the supramanifold nature of existence.',
'Evil is nothing more than live in reverse topsy-whirly with a splash of sugar and a drizzle of honey.',
'I heard the souls&#039; smells through the microwaved energy of ants whispering through the walls that separate me from you.',
'The Haas avocado is out of possession and out from qualifying from the engagement so take your time.',
'Now comes the agony and despair of the egg burnt to a crispy bacon.',
'I cannot keep finding an addiction for excuses for him in the interim between graduation and finally finding yourself.',
'There was only a tiny little bit of throttle left between the bad luck draining me and the bad news.',
'We got a good ear for cars so it will be good so long as you  go over the edge.',
'Both you and Kevin look like you have a strong bridge between the two of your trucks.',
'Be careful not to lose the rear because it tends to spin away from the meta torque.',
'You know you are the strongest when you have all the eggs to break and all the chickens to place.',
'If you have never experienced this lightning bolt on a cosmic scale, it can be difficult to reflect.',
'Stab my fall and I will stab your fall, which in the end, will result in nothingness.',
'A secret plot in the charming saddle block anesthesias slammed those lacrimal sacs.',
'An enlisted woman on the adductive pitch blackness navigated an animatism.',
'Some spatula-shaped floricultures on the trap destressed the bad park in Tokyo, Japan to the delight of the local flora.',
'A fight in a Malaysian straightenned some rosy-colored flags that whipped strongly in the wind.',
'The imbricated throat in an alarming fire brigade queried a Circassian Crusader on horseback.',
'Some affixal icicles in a wintertime erred some white yams and purple taro.',
'The virtuous sweetener in the ambulatory vase glorifies a downmarket graveyard, generating a serene sense of finery.',
'Those cherries in a flying iron boot pursue some Plautuses, skipping about determinely in a whipsaw motion.',
'Some stingy snows in those scriptural contraptions construct a Lygodium palmatum at this stage of the season.',
'An alleviated lowlife in the juicy coach tomorrow reinforces courageous jars&#039; desire to keep staying in the game.',
'Both laces on the wooden-headed fog demoniacally redressed some hats, leaving no one seriously injured.',
'The honest-to-goodness vest solidly shrugs some lumbers, leaving no fatalities, allowing his godson to make his debut.',
'Fangs in the visitants on many dolls officially persuade the bird to take on the unique challenge.',
'I hope this expense report contains all the relevant Sauber ants&#039; dances because I&#039;m not shilling out any more brochures.',
'The first time Mary ever saw Tom across the wall in the achievement results, it was 2010 in March.',
'I hate to trouble you, but I need to rumble you to get in the way, blocking the oncoming myths.',
'An organization and its suppliers are interdependent gold cuban chains, which was honestly quite impressive.',
'Every week we get further from the plain Greek yoghurt of the ancestors of the future.',
'Tony ate his meals in the kitchen shoe and fell to last place, leaving him a teenager with mental strength.',
'It&#039;s the second glance that ties your hands as darkness pulls the string cheese that spins aerially.',
'There is a presumption that any group, anywhere, should be able to reach any overseas diplomatic relationship.',
'If your company primarily does business with America, then you should be studying dance sewing.',
'The favorite family member on your father&#039;s right sided family ought to be the god platypus.',
'Conceited people lose control of all the grants, hitting the back of the tractor.',
'Tom knew that people were whispering the lyrics of the gorilla anthem as the funeral procession passed by.',
'I have a feeling that Tom doesn&#039;t like Mary all that much considering she is trying to do merengue cake.',
'His broken arm was the result of a slip of the tongue in front of the most distinguished academy members.',
'You can be charged with criminal assault without even opening your ears to the situation.',
'Tom and Mary told everyone they were planning to start a mining operation in Boston with a few apple keys.',
'Laser printers are generally less expensive to maintain the same level of fire engines.',
'When my interview was postponed through the temple of speed, I knew it was time for a second practice.',
'As a matter of fact, he knows very little stringe cheese tops.',
'I would have expected to see the confidence dribble from his mouth.',
'I am the only Brazilian bear that speaks with the utmost desire to onboard.',
'Tom, Mary, John and Alice were sitting around the cheese wheel to dominate.',
'I can hide that no one will think of dealing with the elevator slamming shut on the Olympics.',
'A couple loaves far ranged veins of data presented in his book are not based on scientific observations.',
'Cribs politely hold back the cat, who sold him the murder weapon, which makes you an accessory to uxoricide.',
'The conjuration in a squeaky tub cajolingly pops fucking ghosts, which is seen with the naked eye.',
'A few rifles on the broken hydrants shrilly waste the guilty bike that the Church acknowledges as an entity.',
'A sticky camp shyly recognises many crooked acoustics, so please let me know.',
'I visited her with a view to offer an afterthought, which enthusiastically crept many precipitous cabbages.',
'Families moonily noticed a hungry food of river flowing into the Dead Sea.',
'Tom is fishing for trout, while the smooth zebra in the law nonchalantly boiled a well toad.',
'The hurt galleys deliberately located unusual jacks who are loved by men and women alike.',
'Faint sisters annually recorded a couple creams that he used all his strength to crawl.',
'Those beads on healthy steps in the enthusiastic test partly ensued the demode breads.',
'The toothpaste bravely gains some obnoxious natal days besides temporary leave from job.',
'Frantic norths hopelessly disappear a greasy resort area as they turn sharply into the wall.',
'Woods keenly grabbed both creators as the skipped wheel to wheel, pulling ahead.',
'The crib regularly afforded the fireman, so that they could keep pushing pressure in the battle.',
'A few stars strictly emerge a foot in the nexus of the quantum mechanical field.',
'Cars in the scared sack mechanically recover those honeys that remind me of the big lock-up days.',
'The wrist speedily occupies the rapid corn that was done speedily up in time for a switch-a-roo.',
'Some creators in those eerie breads wetly incur the amused red actions.',
'The pan in a mailbox on those crows lively merges left stages.',
'Many spanners obnoxiously suspended crushed crooks, which left an intense tunnel vision.',
'Those pockets in some cacti keenly praised husky pockets, like a eel swimming in olive oil.',
'The pokey in the laborer helplessly isolated obnoxious stars with sixteen feats to go.',
'A few dry wintertimes by choice arised those alert chins that need to be pushed.',
'Some quiet quilts in a few flocks daily succeed a troubled queen.',
'The streams uselessly qualified clams without any rhyme or reason that I could witness.',
'The terrific arm of the shy men utterly shoots the crying mother.',
'Both arrogant earthquakes in arms victoriously sensed the tense maid in armor.',
'Pollution in the string gently free the dying goose of any constraints.',
'An icy plant in adult females excitedly spelled many lettuces and almond nuts.',
'Some petite calendars in the necropoli extremely abandonned slaves in the mines.',
'The golden brains oddly sound the linen with an unkind touch of peace.',
'Beggars swiftly recognise even names in a sea of sandwiches that are well-deserved.',
'Both hushed scents instantly embodied both languages with a keen sense of Ferrari.',
'Those noisy crowds naturally kick the volcano with perhaps too much enthusiasm.',
'Those pans in those happy honored names tremendously pucker the sparkled apparel.',
'A scarecrow on a couple short wants cleverly miss a coming carpenter.',
'Eyes calmly connect a sore basket with an aching fire that spans the world.',
'The book of islands easily filed a strange book as the librarian looked on.',
'A fat snail in the quick calendar months bleakly rolled a couple sugars.',
'The comfortable arithmetic on the songs only praised the hungry, long voyages.',
'The toe energetically analyses the grotesque, grim bedroom with raw American power.',
'Many tricks wearily admire ripe twigs although with a brutal acceptance never seen before.',
'A birthday loosely process some broken islands anf a few shards of honesty.',
'A crib usually initiates the swings from the stars and ambulance money.',
'A dirty heart never performed some throats with the Mongolians in the back.',
'Strange eyes in all probability flooded those blonde writers with a sensation.',
'A bird tenderly attacked a playground, doing a deep dive with a rub down.',
'The creepy sidewalk in a jagged son physically centred bitter sesses harmoniously.',
'A couple cool homes unbearably rule a fresh pleasure, creating an up-and-down waveform.',
'Sidewalks warmly heated those obnoxious carpenters as he golfed eagerly in Austin.',
'An island surprisingly outlined wildernesses thatTom quietly opened the sliding creeper shoes.',
'Both suns merrily contact a scarf joint when he speaks French, which is not a good look.',
'The book deeply twisted a summer song into a nightmare at the moment.',
'A boiling circle on an outstanding vase in a guitar in a rich encephalon solemnly staged the bumpy soil.',
'The delicious crown of those outgoing books miserably shipped some husky feet due to the fear of clowns.',
'The relaxed nerves bleakly connect a couple tense quicksands, although I just wanted to hold her hands.',
'Both long novices in a few vivacious ways softly exhaust those chilly rabbits as they designed uniforms.',
'Shrill mothers wearily dumped those early territories as soon as possible due to the state-owned nature.',
'The young book of the afraid shapes avariciously curled a vase credibly.',
'A cactus of a table sadly borrowed a modern desk, losing the devil in his soul.',
'Dears shakily bother a lumber, so I&#039;m not coming in today at all.',
'Bedrooms on the destitute park jealously exert toothpaste so that the person can move on.',
'The accident happened such that the corrupt yards in a few condemned sons unethically represented the fireman.',
'A couple different contrivances of those stations delightfully toured those basketfuls at home.',
'You&#039;re being unreasonable just because those gloves powerfully repaired the speckle dreadfully.',
'It&#039;s an old custom, where rain in many deafening galleys utterly convict a slave.',
'Tom doesn&#039;t know when Mary got married because of he preoccupised with some right jellyfish.',
'The pavement fatally hurries many different wishes when she waved me aside.',
'Big Brother is watching if not for a couple lonely bodily functions regrettably lack something.',
'The epithet in a wooden jellyfish in vivacious rewards readily purchases the dock.',
'The airplane in many ferocious deer utterly confronted those successful sons by being absolutely ruthlessly.',
'Laces on some good mothers kindheartedly summon the recess, making them the pure racer.',
'Those bedrooms generally painted the anger, transforming the fortunes of all those involved.',
'The star honestly laid the basket at the feet of hundreds of years with the whole of scientific knowledge.',
'The shiny queen on a few dusts mortally pauses the bed as she approached for the assassination.',
'His name is mud, so many cheerful cubs felt no guilt in the mint seemingly spread the treatment.',
'The receptive pencils on some creams fully threaten a defiant plant based on their familiarity with the situation.',
'We try to explain things across cultures because sleets mechanically fired friendly territories.',
'The bland daughter actually recompensed a couple sheets since I said I would like tea or coffee.',
'Tom is out cold as a frantic yard in some bright faces promptly communicated those rapid beggars.',
'A battle angrily summons the parent to wake up the stealthy mint leaves',
'A hissing earthquake reluctantly doubted the galley as she served afternoon tea with scones.',
'Those bumpy pears inside motivate a helpful marble just in time for dinner time without any compromises.',
'A fleeting glimpse of eternity drove a couple troubled dogs in a mount to mysteriously run off a different bath.',
'The scared ghost on the face of it pleads the delightful ball as they climbed a mountain to Vienna.',
'Some long lunchrooms on a determined reward upright appealed petite robins, so you&#039;ll have to ask her that.',
'Both wildernesses lazily derive a spoon with just a few hours to finish this report.',
'I kind of enjoyed ensuring that grapes even hasten an ill rock while they stay stationary for five seconds.',
'An outgoing fight generally preserves a jealous lettuce with a shut up penalty.',
'The cub owlishly dated the stone&#039;s throw, so it could have been much worse.',
'The sleepy desk lazily flexes the girls, so make sure you&#039;re all sufficiently rested.',
'Hot roses in a distinct pencil obnoxiously qualify crayons, allowing them to make it up to sixth place.',
'The narrow grandfather rightfully calms the tiny wrench so make sure that there aren&#039;t any problems in a split second.',
'Those rapid mints in the horrific sugar greedily hunted the rainstorm when they boxed for the pitstop advantage.',
'A parent in a loud veggie properly located throats during the career of a lifetime unfortunately at the last moment.',
'A couple fierce cattles on a few jagged islands angrily sealed both warm cakes.',
'The acoustics in drab milks loftily peered those flocks which lifted the weight from the clouds to create a moment.',
'Both motionless trees quickly back the sheet to keep the dream alive to be a champion.',
'Pies zealously sail those successful judges to take that successfully on the loud chest.',
'The animals voluntarily head repulsive treatments, like you are beaten up on your seat.',
'The sea in a cellar not situated a few snails, so it may not just be the right time.',
'Some pleasant desks gladly perform a befuddled face with his baffling talents and charm.',
'The dog on summers tightly shouts the crown to match the rose and hope of all our wishes.',
'Some squeaky kites in the cactus deliberately strained the flavor in an absolute blur.',
'The busy bean in those uptight achieves joyously orderred those squeaky shows for a big crash.',
'The gun inquisitively mixed bright doctors to create the highest of lows and the lowest of highs majorly.',
'The curious dust in the clear-cut table in dogs badly adopts the right pest.',
'The breezy boy slowly tempts a few suns as they salvaged any attempt to push for another difficulty.',
'A galley in a cooing class separately entitled the lunchroom to give you what you deserve.',
'The army queasily sings the acoustic so that they can maintain the same caliber without retirement.',
'The cacti in the large bun righteously convinced summers to keep the same good steps for the fifth year.',
'Those rivers on the afternoons gleefully convert the apple as they absolutely go for it without any cause for concern.',
'Evil flavors less spell the vests as we head into Abu Dhabi in March under the dramatic lights.',
'A few clever governors gleefully attached some smart as a whip aftermaths for every person.',
'The bound on an elegant mother reluctantly sped puzzled winters, bidding farewell for the last time.',
'The filthy drug enthusiastically regards a class of its own which is characterized by things out of control.',
'A beautiful book regularly conducted both scarves by expressing a lot of anger and regret.',
'The ripe vest in the afterthoughts unintentionally suits the sisters, proving he still has a lot of victory in him.',
'The sore blush wines patiently mounted a donkey, as he puts on the overalls for the last time.',
'The crowded hoses rudely worried a grubby daughter,  reckoning she would be slower in equal machinery.',
'Rooms soon pretended a jagged shape as they showed no fear and gave no quarter.',
'Both streams in a few giraffes deeply realise the courageous borders as they came down the hill precariously.',
'Many eager monies of some snakes dreamfully cared the plastic, leaving no room for comment.',
'Pigs wrongly dedicate a tree to the charismatic fates of the scales in the Grand Prix.',
'Scared months violently emphasise the wild seacoast, leaving them to be closer than was expected.',
'The intervention on a recess unnecessarily instructed the earthquakes in the final start of this season.',
'Those poised tables that were elegantly poised in crooks wilfully reassured the obnoxious notebooks obviously and emotionally.',
'Homely horses in some cloudy lights in a bed vacantly strike parks, which has been a great mystery.',
'Plastic foods sweetly invoked a quilt of life as we all moved on with the red hot solar engine.',
'The mother continually stripped agreeable laces as she hunted for her teammate, fancying a go.',
'The station in stormy spies briefly hangs those lettuces and red cabbages as the crowd cheered on sensibly at it.',
'The fierce sleet loudly dominated the former interventions in the same wing mirrors that they have been closing in on.',
'Both force fields on a dad likely discoverred a couple wishes for all the points in the world championship.',
'Those outgoing blanks questionably strengthenned the naughty traffic jam, causing the crew to come out behind to pull ahead.',
'A couple passengers sedately administerred a stale mom to the engine, taking it off the body without any problem.',
'The purring brother in the anger hopelessly delayed the helpful table, forcing the bulls to really go right together.',
'A few panicky founders of those frantic, sparkly guides precisely illustrated the cheerful thrill with their strength of character.',
'A map of an anxious apple badly debunks the confounded road as they enjoyed the comedown from the application.',
'Holding off the challenge, the shiny star weakly promised the agleam beads the shine of a dimly lit lifetime.',
'The class punctually swings the measured thrill that we need to close the gap in commitment.',
'A red-hot swing in both different days well rings a damaged joke in a surprising squeeze.',
'Sweaters cheerfully exhibit a comfortable dinner as they sat down for the expectations to complete the awkward mission successfully.']

sense=['It&#039;s not possible to convince a monkey to give you a banana by promising it infinite bananas when they die.',
'There have been days when I wished to be separated from my body, but today wasn’t one of those days.',
'While all her friends were positive that Mary had a sixth sense, she knew she actually had a seventh sense.',
'You&#039;ve been eyeing me all day and waiting for your move like a lion stalking a gazelle in a savannah.',
'It was terribly cold and nearly dark on the last evening of the year, and the snow was falling fast.',
'Internal division within the Labor Party was one of the factors which led to its defeat at the recent election.',
'While your friend holds you affectionately by both your hands you are safe, for you can watch both of his.',
'Sometimes, in the still of the night, I imagine how much better the world could be if everyone learned Esperanto.',
'There is a presumption that any group, anywhere, should be able to reach any overseas location with the new technologies.',
'She covers her arms and legs with lye every day, burning and itching and thinking "I&#039;m gonna look so good."',
'There are people in the world so hungry, that God cannot appear to them except in the form of bread.',
'I&#039;m sorry if this distresses you but I can&#039;t afford to pay the sum of money you&#039;re asking from me.',
'I have spent most of the day putting in a comma and the rest of the day taking it out.',
'A human being is a part of the whole, called by us "Universe," a part limited in time and space.',
'Accuracy and finish will become more important than high rates of metal removal for 95 percent of all machining operations.',
'And, though many people seemingly still have not noticed this, Esperanto is not a project anymore; it is a language.',
'Do not fear that which is the final end of life: he who fears death eschews the joys of life.',
'New Zealand is known as "The Shaky Isles" because of its location on the margin of two colliding tectonic plates.',
'The school is not quite deserted," said the Ghost. "A solitary child, neglected by his friends, is left there still.',
'Tom and Mary purchased a small parcel of land on the edge of town, where they plan to grow vegetables.',
'How do you make a triangle-shaped onigiri? No matter how many times I try I can only make round onigiri.',
'He learned the hardest lesson of his life and had the scars, both physical and mental, to prove it.',
'He learned the important lesson that a picnic at the beach on a windy day is a bad idea.',
'If you like tuna and tomato sauce- try combining the two. It’s really not as bad as it sounds.',
'She can live her life however she wants as long as she listens to what I have to say.',
'The urgent care center was flooded with patients after the news of a new deadly virus was made public.',
'Thirty years later, she still thought it was okay to put the toilet paper roll under rather than over.',
'An aviary is a large enclosure for birds, often containing shrubbery and other plants to simulate their natural habitat.',
'Only when the Party Committee Secretary came in person to resolve it was this point of view dispelled entirely.',
'That part of the film that&#039;s very critical of the internal politics of the government was rejected by censorship.',
'"We have no doubt his liberality is well represented by his surviving partner," said the gentleman, presenting his credentials.',
'When Mary told her parents that she wanted to marry Tom, they said that they wouldn&#039;t attend the wedding.',
'I hope to contact other Esperantists through the radio, as I&#039;m a radio amateur. My call sign is F5NQW.',
'Often, the less there is to justify a traditional custom the harder it is to get rid of it.',
'After a while, I could not help noticing we did not seem to be walking on the path anymore.',
'He had a yeoman, but no other servants at that time, because it pleased him to ride that way.',
'He has been told by the doctor to give up smoking, but he cannot seem to give it up.',
'We just have to put the finishing touches to the work, and it will be ready to be delivered.',
'The Portuguese Vasco da Gama discovered the seaway that leads from Portugal, around the continent of Africa, to India.',
'Peeling an orange can be tricky at times, you never know if it will squirt you in the face.',
'Svetlana was a little too merciful with the feeder mice down at the pet store, so the snakes starved.',
'If two past lovers can remain friends, it&#039;s either because they are still in love, or they never were.',
'Paradoxically, the President of Turkey is the de jure head of state but has no legal role in government.',
'If you have complaints about the taste of my cooking, you could start to make it yourself starting tomorrow.',
'He turned out to be a real disappointment after we went through hell and high water to find him.',
'As he entered the church he could hear the soft voice of someone whispering into a cell phone.',
'As the rental car rolled to a stop on the dark road, her fear increased by the moment.',
'As time wore on, simple dog commands turned into full paragraphs explaining why the dog couldn’t do something.',
'He played the game as if his life depended on it and the truth was that it did.',
'He was the type of guy who liked Christmas lights on his house in the middle of July.',
'He would only survive if he kept the fire going and he could hear thunder in the distance.',
'She saw no irony asking me to change but wanting me to accept her for who she is.',
'The clock within this blog and the clock on my laptop are 1 hour different from each other.',
'The newly planted trees were held up by wooden frames in hopes they could survive the next storm.',
'The teens wondered what was kept in the red shed on the far edge of the school grounds.',
'They say that dogs are man&#039;s best friend, but this cat was setting out to sabotage that theory.',
'I don&#039;t see how Tom can stay up all night and then be so wide awake at work.',
'For many years, the abbey was turned into a fortress, happily joining in itself martial and religious architecture.',
'The grief-stricken family had to wait more than a decade to see their son&#039;s killer brought to justice.',
'After that newspaper wrote that no farmer wanted to work as a tenant in Vestfold, interest has skyrocketed.',
'Although her parents had said no for a long time, they finally let her go to Europe alone.',
'Until 1986, in the schools of England, it was legal to punish children with belts, sticks, and clubs.',
'I think it strange that there is no one on the street at this time of the day.',
'The chair gave way as Tom sat on it, and he crashed to the floor injuring his back.',
'The woman did not say anything; she just buried her face in her hands and burst into tears.',
'The JMdict/EDICT project has as its goal the production of a freely available Japanese-English Dictionary in machine-readable form.',
'Tom spent a very enjoyable hour watching his grandson playing on the equipment at the shopping mall playground.',
'After graduating from college my brother went to the United States for the purpose of doing further research.',
'I didn&#039;t know that there was this sort of place just on the route to the high school.',
'She said that she had things that she needed to do and that she would be back later.',
'For over a year the bottle drifted about, now north, now south, as the ocean&#039;s currents drove it.',
'I said, I will go up to the palm tree, I will take hold of the boughs thereof.',
'The door to my room screeches when I open it. I wonder if there&#039;s something wrong with it.',
'She tilted her head back and let whip cream stream into her mouth while taking a bath.',
'She wasn&#039;t sure whether to be impressed or concerned that he folded underwear in neat little packages.',
'The group quickly understood that toxic waste was the most effective barrier to use against the zombies.',
'The tattered work gloves speak of the many hours of hard labor he endured throughout his life.',
'The team members were hard to tell apart since they all wore their hair in a ponytail.',
'The Tsunami wave crashed against the raised houses and broke the pilings as if they were toothpicks.',
'You&#039;re unsure whether or not to trust him, but very thankful that you wore a turtle neck.',
'I don&#039;t think Tom is the only one who doesn&#039;t have enough money to buy a ticket.',
'He is so mild in disposition that I have never heard him speak in a loud voice.',
'The thickness of Saturn&#039;s rings ranges from 10 to 100 meters and the rings vary in brightness.',
'Few things can compare to the joy on your child&#039;s face as they open their Christmas presents.',
'All of these resources combined together, could not purchase or equal the value of an eternal life.',
'These maps are the key to who will hold how much power in Illinois for 10 years.',
'I&#039;d like to express my gratitude to all those who have contributed to make my sentences better.',
'I&#039;m sorry to call you this late at night, but I really needed someone to talk to.',
'In the upcoming week I have to go to the doctor to have my sick leave extended.',
'I am sure our dear guest would like to have a bath before he goes to bed.',
'Now that the boy was five, they had to think about which school to send him to.',
'The Princess came out of the copper castle, and became Queen; and that pleased her very much.',
'Tom is facing eviction if he doesn&#039;t pay his back rent by the end of this month.',
'Tom&#039;s very resilient and can always manage to smile, no matter what&#039;s going on in his life.',
'I know you well enough to know that you didn&#039;t really want to go out with Tom.',
'Tom took off his jacket, put on a bullet-proof vest, and then put his jacket back on.',
'Doing nothing is the most difficult thing in the world, the most difficult and the most intellectual.',
'Your arms are more important than that stick, so instead of using your arm, use the stick.',
'The vegetation and the murmuring water calmed my ardent mind as I breathed in and out slowly.',
'I was there when the total solar eclipse left Svalbard in the dark on March 20, 2015.',
'Before he moved to the inner city, he had always believed that security complexes were psychological.',
'He had a wall full of masks so she could wear a different face every day.',
'His thought process was on so many levels that he gave himself a phobia of heights.',
'Honestly, I didn&#039;t care much for the first season, so I didn&#039;t bother with the second.',
'I thought red would have felt warmer in summer but I didn&#039;t think about the equator.',
'Most shark attacks occur about 10 feet from the beach since that&#039;s where the people are.',
'She couldn&#039;t decide of the glass was half empty or half full so she drank it.',
'She did not cheat on the test, for it was not the right thing to do.',
'She is never happy until she finds something to be unhappy about; then, she is overjoyed.',
'The clouds formed beautiful animals in the sky that eventually created a tornado to wreak havoc.',
'The tears of a clown make my lipstick run, but my shower cap is still intact.',
'The two walked down the slot canyon oblivious to the sound of thunder in the distance.',
'He looked out of his brown eyes at the man that had just decided his future.',
'Many people find that their superannuation is not sufficient for them to live comfortably after retirement.',
'I am sending you by mail some brochures that will help you to choose a hotel.',
'After a light swim, I came up from the water and sat down on the poolside.',
'Only when it comes to tenses and phrasal verbs is English grammar more difficult than German.',
'When Mary went to cook dinner, she found that her potatoes had sprouted in the cupboard.',
'If something is given to you then take it. If you are beaten, then run away.',
'At the party the other night, my brother drank a bit too much and passed out.',
'He made it known to his friends that he was unwilling to run for the election.',
'She asked him to not quit his job because they were poor and needed the money.',
'The main protagonists in Tom&#039;s stories are always animals, however the bad guys are always humans.',
'The last I heard, Tom and Mary haven&#039;t yet decided where to go on their honeymoon.',
'Tom shook the bottle as directed on the label, but unfortunately didn&#039;t fasten the cap first.',
'He had a hidden stash underneath the floorboards in the back room of the house.',
'I think I will buy the red car, or I will lease the blue one.',
'If my calculator had a history, it would be more embarrassing than my browser history.',
'Last Friday I saw a spotted striped blue worm shake hands with a legless lizard.',
'Malls are great places to shop; I can find everything I need under one roof.',
'There aren&#039;t enough towels in the world to stop the sewage flowing from his mouth.',
'Wisdom is easily acquired when hiding under the bed with a saucepan on your head.',
'To film the soccer game, we need to find a place with an unobstructed view',
'It is easy to make a man one&#039;s friend, but hard to keep him so',
'The local boys got into a fight with a rival group from a neighboring town',
'Tom didn&#039;t want to disturb Mary so late at night, but it was an emergency',
'Tom wanted to help Mary rake the leaves, but she was using the only rake',
'I was stuck in confinement for thirty days until I decided to pay a bribe',
'He&#039;s a financial analyst with a pretty good reputation for his analysis of economic trends',
'I saw you while you were still under the fig tree before Philip called you',
'How could he possibly have effected that kind of change in that amount of time?',
'I don&#039;t want to go back to school;  I wish summer vacation would never end.',
'Kangaroo tail soup is known as an Australian dish, because kangaroos are found in Australia',
'To avoid electrical shock, do not open the cabinet-- Refer servicing to qualified personnel only.',
'We&#039;ve been moping around too much-- It&#039;s time to pull ourselves together and keep trying.',
'Romney said the Obama campaign had been "reduced to petty attacks and silly word games."',
'I make it a rule to take a walk for half an hour every morning.',
'Even though Bob was in disguise, I recognized him as soon as I saw him.',
'I saw her for a moment, but then lost sight of her in the crowd.',
'Tom, an experienced reporter, was investigating the recent abduction of three children in the city.',
'Tom Jackson&#039;s new novel is very well written and I&#039;m sure you&#039;ll enjoy reading it.',
'I had no school today, so I spent the whole day at home watching TV.',
'Even with the snow falling outside, she felt it appropriate to wear her bikini.',
'For oil spots on the floor, nothing beats parking a motorbike in the lounge.',
'He found his art never progressed when he literally used his sweat and tears.',
'He picked up trash in his spare time to dump in his neighbor&#039;s yard.',
'He stepped gingerly onto the bridge knowing that enchantment awaited on the other side.',
'He wondered if it could be called a beach if there was no sand.',
'If any cop asks you where you were, just say you were visiting Kansas.',
'Jason lived his life by the motto, "Anything worth doing is worth doing poorly.',
'People generally approve of dogs eating cat food but not cats eating dog food.',
'She borrowed the book from him many years ago and hasn&#039;t yet returned it.',
'She let the balloon float up into the air with her hopes and dreams.',
'She was amazed by the large chunks of ice washing up on the beach.',
'She was the type of girl that always burnt sugar to show she cared.',
'The complicated school homework left the parents trying to help their kids quite confused.',
'The fog was so dense even a laser decided it wasn&#039;t worth the effort.',
'The Guinea fowl flies through the air with all the grace of a turtle.',
'The sign said there was road work ahead so he decided to speed up.',
'The snow-covered path was no help in finding his way out of the back-country.',
'When he asked her favorite number, she answered without hesitation that it was diamonds.',
'When money was tight, he&#039;d get his lunch money from the local wishing well.',
'Whenever he saw a red flag warning at the beach he grabbed his surfboard.',
'She went to the store in the dead of the night for some reason.',
'You&#039;re going to look like a lobster if you don&#039;t put on some sunscreen.',
'You have to wait on a long line to get into the Louvre Museum.',
'This is the only guidebook that was recommended to me that is really useful.',
'This is the first time I&#039;ve climbed this mountain. The sight is really awesome.',
'A picnic at the beach on a windy day is a bad idea.',
'At that moment he wasn&#039;t listening to music, he was living an experience.',
'David proudly graduated from high school top of his class at age 97.',
'Edith could decide if she should paint her teeth or brush her nails.',
'Going from child, to childish, to childlike is only a matter of time.',
'He kept telling himself that one day it would all somehow make sense.',
'His mind was blown that there was nothing in space except space itself.',
'His son quipped that power bars were nothing more than adult candy bars.',
'I am happy to take your donation; any amount will be greatly appreciated.',
'I don’t respect anybody who can’t tell the difference between Pepsi and Coke.',
'I met an interesting turtle while the song on the radio blasted away.',
'Karen realized the only way she was getting into heaven was to cheat.',
'Never underestimate the willingness of the greedy to throw you under the bus.',
'Peanut butter and jelly caused the elderly lady to think about her past.',
'She insisted that cleaning out your closet was the key to good driving.',
'The efficiency we have at removing trash has made creating trash more acceptable.',
'The green tea and avocado smoothie turned out exactly as would be expected.',
'The light in his life was actually a fire burning all around him.',
'The minute she landed she understood the reason this was a fly-over state.',
'The three-year-old girl ran down the beach as the kite flew behind her.',
'The tortoise jumped into the lake with dreams of becoming a sea turtle.',
'When he encountered maize for the first time, he thought it incredibly corny.',
'It took me a while to understand what she was trying to say.',
'They searched high and low for the missing boy but to no avail.',
'I just got a beautiful bunch of flowers from one of my clients.',
'Tom looked at the price tag and realized he didn&#039;t have enough money.',
'He didn&#039;t heed the warning and it had turned out surprisingly well.',
'He ran out of money, so he had to stop playing poker.',
'He was the type of guy who liked Christmas lights year round.',
'I was about to go out when he came to see me.',
'Tom told me his father was pretty good at playing the guitar.',
'Bigots are incapable of discriminating, since they lump individuals into homogeneous groupings',
'He believed that the war was fought in the cause of justice.',
'Sorry that I&#039;ve reduced you to someone to drag my luggage around.',
'I&#039;m sorry, but the manager won&#039;t be able to see you now.',
'Honestly, I wish it was okay for men to wear fancy earrings.',
'It seems that my little sister got her wallet stolen at school.',
'Tanaka has said that he got up this morning around eight o&#039;clock.',
'Well, of course, I would never doubt that my coach is right.',
'All men who are lonely are lonely because they&#039;re afraid of others.',
'The blue of her eyes stands out against her rather dark skin.',
'Tom is probably just making a mountain out of a molehill again.',
'I can&#039;t tell whether it landed upside down, inside out, or backwards.',
'The weather has been on and off here for a few days.',
'The problem is not what he said, but how he said it.',
'A liar will not be believed, even when he speaks the truth.',
'Thousands of migrants decided to walk from Budapest in Hungary to Austria.',
'I can&#039;t help but wonder if Tom will be at school tomorrow.',
'I&#039;d be almost there by now if I&#039;d left right after breakfast.',
'Tom and Mary sat at the dining room table facing each other.']

import random
import numpy as np
random.shuffle(sense)
random.shuffle(nonsense)
N=0
N2=0
listS=[[] for i in range(int(len(nonsense)/22))]
listJ=[[] for i in range(int(len(nonsense)/22))]
for i in range(int(len(nonsense)/22)):
	judge=np.concatenate([np.zeros(22),np.ones(22)],0)
	random.shuffle(judge)
	listJ[i]=judge
	for n in judge:
		if n==0:
			listS[i]+=[nonsense[N]]
			N+=1
		if n==1:
			listS[i]+=[sense[N2]]
			N2+=1

print(listS)
print(listJ)